Implement the reviews

diff --git a/check-environment-and-install b/check-environment-and-install
--- a/check-environment-and-install
+++ b/check-environment-and-install
@@ -1,20 +1,22 @@
 #!/bin/bash
 
-return_code=0
+[ "${BASH_SOURCE[0]}" != "$0" ] && { echo "ERROR: this script must be executed by Bash, neither source'd nor executed by a different shell"; return 1; }
+
+exit_status=0
 if [[ -n "${BROWSER_DRIVER_INSTALLER_CHROME_VERSION:-}" && -n "${BROWSER_DRIVER_INSTALLER_CHROMEDRIVER_PATH:-}" ]]; then
     npx browserDriverInstaller --browser-name Chrome                                                \
                     --browser-version "$BROWSER_DRIVER_INSTALLER_CHROME_VERSION"                    \
-                    --target-path "$BROWSER_DRIVER_INSTALLER_CHROMEDRIVER_PATH" || return_code=$?
+                    --target-path "$BROWSER_DRIVER_INSTALLER_CHROMEDRIVER_PATH" || exit_status=$?
 else
-    echo "The environment variables for Chrome are not set, skipping post-install for Chrome"
+    echo "The environment variables for Chrome (\$BROWSER_DRIVER_INSTALLER_CHROME_VERSION, \$BROWSER_DRIVER_INSTALLER_CHROMEDRIVER_PATH) are not set, skipping the installation step for Chrome"
 fi
 
 if [[ -n "${BROWSER_DRIVER_INSTALLER_FIREFOX_VERSION:-}" && -n "${BROWSER_DRIVER_INSTALLER_GECKODRIVER_PATH:-}" ]]; then
     npx browserDriverInstaller --browser-name Firefox                                               \
                     --browser-version "$BROWSER_DRIVER_INSTALLER_FIREFOX_VERSION"                   \
-                    --target-path "$BROWSER_DRIVER_INSTALLER_GECKODRIVER_PATH" || return_code=$?
+                    --target-path "$BROWSER_DRIVER_INSTALLER_GECKODRIVER_PATH" || exit_status=$?
 else
-    echo "The environment variables for Firefox are not set, skipping post-install for Firefox"
+    echo "The environment variables for Firefox (\$BROWSER_DRIVER_INSTALLER_FIREFOX_VERSION, \$BROWSER_DRIVER_INSTALLER_GECKODRIVER_PATH) are not set, skipping the installation step for Firefox"
 fi
 
-exit $return_code
+exit $exit_status
